// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD2XxMZEtrh-YjP3bBlod27pzVjQPB4Bg',
    appId: '1:682820949159:web:b1c0dafdf8e020997ab782',
    messagingSenderId: '682820949159',
    projectId: 'guezs-films',
    authDomain: 'guezs-films.firebaseapp.com',
    storageBucket: 'guezs-films.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgYuhnbUrKu4hU0BMzlEcEpS-IAHliAXU',
    appId: '1:682820949159:android:decef4fadfb26a7a7ab782',
    messagingSenderId: '682820949159',
    projectId: 'guezs-films',
    storageBucket: 'guezs-films.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJBKVOGMf_i7zusEduio4tqfqID1x82vY',
    appId: '1:682820949159:ios:53c93124d0d86ffc7ab782',
    messagingSenderId: '682820949159',
    projectId: 'guezs-films',
    storageBucket: 'guezs-films.firebasestorage.app',
    iosBundleId: 'com.guezfilms.app',
  );
}
